name: easy_life_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  logger: ^2.5.0
  flutter_secure_storage: ^9.2.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dio: ^5.2.0
  cached_network_image: ^3.2.0
  json_annotation: ^4.8.0
  pine: ^1.0.4
  pretty_dio_logger: ^1.4.0
  auto_route: ^9.2.2
  provider: ^6.1.5
  retrofit: ^4.4.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.26.1
  build_runner: ^2.4.13
  bloc_test: ^10.0.0
  retrofit_generator: ^9.1.5
  auto_route_generator: ^9.0.0
  http_mock_adapter: ^0.6.1
  data_fixture_dart: ^3.0.0
  mockito: ^5.4.6

flutter:
  uses-material-design: true
